### ISSUE TITLE
JSON files not found.

### ISSUE THREAD

**Issue by akshaysgithub** [Antontelesh/mochawesome-merge#51]
Hello, 

I want to create a single html file with the library. It's failing to find the json files. I can see that the json files are generated. 

Error : 

`2 Running command yarn mochawesome-merge > mochawesome.json`

I tried going one directory up as well, no luck 

`Running command cd $PWD/cypress/report/`

I can see that the json file is there. 

```

mochawesome] Report JSON saved to /codebuild/output/src308570643/src/github.com/company/magento-cypress/cypress/report/mochawesome-report/mochawesome_08142020_142823.json

[mochawesome] Report HTML saved to /codebuild/output/src308570643/src/github.com/company/magento-cypress/cypress/report/mochawesome-report/mochawesome_08142020_142823.html
```
Buildspec.yml 
```

version: 0.2
env:
  variables:
    BUILD_DIR: "."
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i
      - apt-get update && apt-get install -y yarn libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
      - yarn install
  build:
    commands:
      - ls -al
      - pwd
      - npx wait-on http://localhost:3000 &
      - npx cypress run --env MAGENTO_HOST=COMPANYDOMAIN.com
      - cd $PWD/cypress/report/
      - yarn add mocha@5.2.0 mochawesome mochawesome-merge
      - yarn mochawesome-merge > mochawesome.json
      - yarn marge mochawesome.json
      - aws s3 sync $PWD/cypress/report/mochawesome-report/ s3://cypress.company.com/
```

What am I doing wrong? Any ideas. Thank you. :-)
